### ISSUE TITLE
Remove elements from ICP-MS raw data

### ISSUE THREAD

**Issue by alebastianoni** [giovannellilab/geochem#39]
Remove the following metals from the list:
Li [He] and Li [No Gas]
Na [ No Gas ]
Mg [ No Gas ] and Mg [ He ]
P [ No Gas ]
S [ No Gas ]
K [ No Gas ] and K [ He ]
Ca [ He ] and Ca [ No Gas ] and 
Si [ No Gas ]

**Comment by guillecg** [comment]
Addressed in 49931c2139bf09b850cc0ccf77294854eea86b97
