### ISSUE TITLE
Change the color palette

### ISSUE THREAD

**Issue by alebastianoni** [giovannellilab/geochem#40]
"#2E83AD",
    "#66C2A5",
    "#ABD9E9",
    "#E6F598",
    "#FFFFBF",
    "#FEE08B",
    "#FDAE61",
    "#F46D43",
    "#D53E4F", --> Co 
    "#9E0142",
    "#8E0152",
    "#C51B7D", --> Cu
    "#DE77AE",
    "#F1B6DA",
    "#FDE0EF",
    "#e08214", --> Fe
    "#F7F7F7",
    "#D9F0D3",
    "#A6DBA0",
    "#5AAE61",
    "#1B7837", --> Mn
    "#00441B", -->Mo
    "#4D9221",
    "#7CB85C", --> Ni
    "#A6D96A",
    "#D9EF8B",
    "#FFFFCC",
    "#FDAE61",
    "#F46D43", --> Se
    "#D73027",
    "#A50026",
    "#67001F",
    "#EF8A62",
    "#F7F7F7",
    "#67A9CF",
    "#D0E1F0",
    "#FFFFB3",
    "#F0F0F0",
    "#B3DE69", --> V
    "#8DD3C7",--> W
    "#80B1D3",
    "#5E4FA2",
    "#BEBADA", 
    "#FDB462",--> Zn
    "#FB8072"

**Comment by guillecg** [comment]
I would need a data.frame with the following columns: element, type, color

**Comment by alebastianoni** [comment]
Here's the data.frame
[element_list_color_palette.csv](https://github.com/giovannellilab/geochem/files/15318494/element_list_color_palette.csv)

**Comment by guillecg** [comment]
Solved in 74e9eab4877bd0322c52a134f67f886defafc894
