### ISSUE TITLE
Convert new IC values from ppm to meq

### ISSUE THREAD

**Issue by guillecg** [giovannellilab/geochem#49]
- [ ] Calculate meq
- [ ] For bicarbonate, multiply by 1.22

**Comment by alebastianoni** [comment]
Normalize meq to %
 - [ ] Sum Na+K
 - [ ] Normalize Ca Mg Na+K to 100%
 - [ ] Normalize HCO3 + SO4+ Cl to 100%
 
When in doubt check this:
https://inside.mines.edu/~epoeter/_GW/18WaterChem2/WaterChem2pdf.pdf

**Comment by guillecg** [comment]
Addressed in a94978f71062aff769f6b3bf65588c298a6b739d
