### ISSUE TITLE
Include bubble plots of field data to add to the Exp Report

### ISSUE THREAD

**Issue by alebastianoni** [giovannellilab/geochem#54]
Add the plots that should be included in the Expedition Report according to the GRL Expedition Report template of the Glab.
#pH vs T with alkalinity colored by rock type
ggplot(env_data_df, aes(x=temp, y=ph, size=hco3, color=rock_type,stroke=0.25)) + 
scale_size(range = c(1, 20), name="Total Alk (mg/L)") +
    geom_point(alpha=1)+
scale_color_manual(env_data_df$rock_type,
                  values=c("#238443","#c6dbef","#fed976","#d7b5d8"),
                  breaks=c("siliciclastic","evaporitic","rhyolitic","granitic"))+
geom_text(aes(label= ID), 
          colour = "black",
          size=2.5, 
          hjust =-1.5,
          vjust =1.5, 
          check_overlap = F)+
labs(title="",
     subtitle="",
     color="Rock type",
     y="pH",
     x="Temperature (°C)",
     size= "Total Alkalinity (mg/L of bicarbonate)")+
theme_glab(base_size=20)

**Comment by guillecg** [comment]
Solved in bfcdae0a2bbbc8311762654ad4f6c51a48e97f32
